ALTER TABLE t_roles RENAME TO t_account_role;

CREATE TABLE t_account_profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   is_deleted BOOLEAN,
   deleted_at TIMESTAMP WITHOUT TIME ZONE,
   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   created_by VARCHAR(255) NOT NULL,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   updated_by VARCHAR(255),
   fullname VARCHAR(50) NOT NULL,
   email VARCHAR(50),
   phone_number VARCHAR(15),
   address TEXT,
   birth_place VARCHAR(20),
   birth_date date,
   CONSTRAINT pk_t_account_profile PRIMARY KEY (id)
);

ALTER TABLE t_account_profile ADD CONSTRAINT uc_t_account_profile_email UNIQUE (email);

ALTER TABLE t_account_profile ADD CONSTRAINT uc_t_account_profile_phone_number UNIQUE (phone_number);

CREATE TABLE t_account_master (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   is_deleted BOOLEAN,
   deleted_at TIMESTAMP WITHOUT TIME ZONE,
   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   created_by VARCHAR(255) NOT NULL,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   updated_by VARCHAR(255),
   username VARCHAR(30) NOT NULL,
   password VARCHAR(15) NOT NULL,
   id_profile BIGINT NOT NULL,
   id_roles BIGINT[] NOT NULL,
   id_types BIGINT[] NOT NULL,
   CONSTRAINT pk_t_account_master PRIMARY KEY (id)
);

ALTER TABLE t_account_master ADD CONSTRAINT uc_t_account_master_username UNIQUE (username);